# Generated by Django 3.2.19 on 2023-06-15 09:13

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('last_name', models.CharField(max_length=150, verbose_name='last name')),
                ('email', models.EmailField(max_length=254, verbose_name='email address')),
                ('phone', models.CharField(blank=True, max_length=18, validators=[django.core.validators.RegexValidator(regex='^(?:(?:\\+|00)33|0)\\s*[1-9](?:[\\s.-]*\\d{2}){4}$')], verbose_name='téléphone')),
                ('address', models.CharField(blank=True, max_length=128, verbose_name='adresse')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'utilisateur',
                'ordering': ['username'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('order_deadline', models.DateField(blank=True, help_text='Date limite de commande.<br> Si pas définie, elle sera automatiquement fixée à 4 jours avant la Date de Livraison', unique=True, verbose_name='date limite de commande')),
                ('message', models.CharField(blank=True, max_length=128)),
            ],
            options={
                'verbose_name': 'livraison',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='date de création')),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=8, verbose_name='montant')),
                ('message', models.CharField(blank=True, help_text="Message interne seulement visible par l'équipe", max_length=128)),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='baskets.delivery', verbose_name='livraison')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='utilisateur')),
            ],
            options={
                'verbose_name': 'commande',
            },
        ),
        migrations.CreateModel(
            name='Producer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='nom')),
                ('phone', models.CharField(blank=True, max_length=18, validators=[django.core.validators.RegexValidator(regex='^(?:(?:\\+|00)33|0)\\s*[1-9](?:[\\s.-]*\\d{2}){4}$')], verbose_name='téléphone')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'producteur',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='nom')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='prix unitaire')),
                ('is_active', models.BooleanField(default=True)),
                ('producer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='baskets.producer', verbose_name='producteur')),
            ],
            options={
                'verbose_name': 'produit',
                'ordering': ['producer', 'name'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='quantité')),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=8, verbose_name='montant')),
                ('saved_p_name', models.CharField(blank=True, max_length=64, null=True, verbose_name='nom du produit (sauvegardé)')),
                ('saved_p_unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='prix unitaire (sauvegardé)')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='baskets.order', verbose_name='commande')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='baskets.product', verbose_name='produit')),
            ],
            options={
                'verbose_name': 'ligne de commande',
                'verbose_name_plural': 'lignes de commande',
            },
        ),
        migrations.AddField(
            model_name='delivery',
            name='products',
            field=models.ManyToManyField(help_text='A gauche tous les produits. A droite les produits disponibles à la commande pour cette livraison<br>', related_name='deliveries', to='baskets.Product', verbose_name='produits'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.UniqueConstraint(fields=('delivery', 'user'), name='user can only place one order per delivery'),
        ),
    ]
