# Generated by Django 3.2.20 on 2023-09-17 18:32

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Delivery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(unique=True)),
                (
                    "order_deadline",
                    models.DateField(
                        blank=True,
                        help_text="Last day to order. If left blank, it will be automatically set to 4 days before Delivery date",
                        verbose_name="last day to order",
                    ),
                ),
                ("message", models.CharField(blank=True, max_length=128)),
            ],
            options={
                "verbose_name": "delivery",
                "verbose_name_plural": "deliveries",
                "ordering": ["date"],
            },
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "creation_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="creation date"
                    ),
                ),
                (
                    "last_updated_date",
                    models.DateTimeField(
                        auto_now=True, verbose_name="last update date"
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        editable=False,
                        max_digits=8,
                        verbose_name="amount",
                    ),
                ),
                (
                    "message",
                    models.CharField(
                        blank=True,
                        help_text="Internal message only visible by stuff members",
                        max_length=128,
                    ),
                ),
                (
                    "delivery",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="orders",
                        to="baskets.delivery",
                        verbose_name="delivery",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="orders",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "verbose_name": "order",
            },
        ),
        migrations.CreateModel(
            name="Producer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=64, verbose_name="name")),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        max_length=18,
                        validators=[
                            django.core.validators.RegexValidator(
                                regex="^(?:(?:\\+|00)33|0)\\s*[1-9](?:[\\s.-]*\\d{2}){4}$"
                            )
                        ],
                        verbose_name="phone",
                    ),
                ),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "producer",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=64, verbose_name="name")),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=8, verbose_name="unit price"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "producer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to="baskets.producer",
                    ),
                ),
            ],
            options={
                "verbose_name": "product",
                "ordering": ["producer", "name"],
            },
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(
                        default=1,
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="quantity",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        editable=False,
                        max_digits=8,
                        verbose_name="amount",
                    ),
                ),
                (
                    "product_name",
                    models.CharField(
                        blank=True,
                        max_length=64,
                        null=True,
                        verbose_name="product name (saved)",
                    ),
                ),
                (
                    "product_unit_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=8,
                        null=True,
                        verbose_name="product unit price (saved)",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="baskets.order",
                        verbose_name="order",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="order_items",
                        to="baskets.product",
                        verbose_name="product",
                    ),
                ),
            ],
            options={
                "verbose_name": "order item",
                "verbose_name_plural": "order items",
            },
        ),
        migrations.AddField(
            model_name="delivery",
            name="products",
            field=models.ManyToManyField(
                help_text="All products on the left. On the right, products available for this delivery.<br>",
                related_name="deliveries",
                to="baskets.Product",
                verbose_name="products",
            ),
        ),
        migrations.AddConstraint(
            model_name="order",
            constraint=models.UniqueConstraint(
                fields=("delivery", "user"),
                name="user can only place one order per delivery",
            ),
        ),
    ]
