# Generated by Django 3.2.9 on 2021-12-12 13:31

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('baskets', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='delivery',
            options={'verbose_name': 'livraison'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'commande'},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name': 'ligne de commande', 'verbose_name_plural': 'lignes de commande'},
        ),
        migrations.AlterModelOptions(
            name='producer',
            options={'verbose_name': 'producteur'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['producer'], 'verbose_name': 'produit'},
        ),
        migrations.AlterField(
            model_name='delivery',
            name='order_deadline',
            field=models.DateField(blank=True, help_text='Date limite de commande. Si pas définie, elle sera automatiquement fixée à 4 jours avant la Date de Livraison', unique=True, verbose_name='date limite de commande'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='products',
            field=models.ManyToManyField(related_name='deliveries', to='baskets.Product', verbose_name='produits'),
        ),
        migrations.AlterField(
            model_name='order',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=8, verbose_name='montant'),
        ),
        migrations.AlterField(
            model_name='order',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date de création'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='baskets.delivery', verbose_name='livraison'),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='utilisateur'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=8, verbose_name='montant'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='baskets.order', verbose_name='commande'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='baskets.product', verbose_name='produit'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='quantité'),
        ),
        migrations.AlterField(
            model_name='producer',
            name='name',
            field=models.CharField(max_length=64, verbose_name='nom'),
        ),
        migrations.AlterField(
            model_name='producer',
            name='phone',
            field=models.CharField(blank=True, max_length=18, validators=[django.core.validators.RegexValidator(regex='^(?:(?:\\+|00)33|0)\\s*[1-9](?:[\\s.-]*\\d{2}){4}$')], verbose_name='téléphone'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=64, verbose_name='nom'),
        ),
        migrations.AlterField(
            model_name='product',
            name='producer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='baskets.producer', verbose_name='producteur'),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='prix unitaire'),
        ),
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.CharField(blank=True, max_length=128, verbose_name='adresse'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=150, verbose_name='last name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=18, validators=[django.core.validators.RegexValidator(regex='^(?:(?:\\+|00)33|0)\\s*[1-9](?:[\\s.-]*\\d{2}){4}$')], verbose_name='téléphone'),
        ),
    ]
