# Generated by Django 3.2.9 on 2022-01-18 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baskets', '0002_auto_20211212_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='message',
            field=models.CharField(blank=True, help_text="Message interne seulement visible par l'équipe", max_length=128),
        ),
    ]
