# Generated by Django 3.2.9 on 2022-02-28 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baskets', '0003_alter_order_message'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['username']},
        ),
    ]
