# Generated by Django 3.2.9 on 2022-03-09 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baskets', '0004_alter_user_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='delivery',
            options={'ordering': ['date'], 'verbose_name': 'livraison'},
        ),
        migrations.AlterModelOptions(
            name='producer',
            options={'ordering': ['name'], 'verbose_name': 'producteur'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['username'], 'verbose_name': 'utilisateur'},
        ),
    ]
