# Generated by Django 3.2.9 on 2022-10-02 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baskets', '0005_auto_20220309_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='order_deadline',
            field=models.DateField(blank=True, help_text='Date limite de commande.<br> Si pas définie, elle sera automatiquement fixée à 4 jours avant la Date de Livraison', unique=True, verbose_name='date limite de commande'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='products',
            field=models.ManyToManyField(help_text='Produits disponibles pour cette livraison. Par défaut, tous sont séléctionnés.<br>', related_name='deliveries', to='baskets.Product', verbose_name='produits'),
        ),
    ]
