# Generated by Django 3.2.9 on 2022-10-07 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baskets', '0006_add_help_text_delivery_products'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['producer', 'name'], 'verbose_name': 'produit'},
        ),
    ]
