# Generated by Django 3.2.9 on 2022-10-20 14:39

from django.db import migrations, models
import django.db.models.deletion


def init_order_item_saved_p(apps, schema_editor):
    OrderItem = apps.get_model('baskets', 'OrderItem')
    for oi in OrderItem.objects.all():
        oi.saved_p_name = oi.product.name
        oi.saved_p_unit_price = oi.product.unit_price
        oi.save(update_fields=['saved_p_name', 'saved_p_unit_price'])


class Migration(migrations.Migration):

    dependencies = [
        ('baskets', '0007_alter_product_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='saved_p_name',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='nom du produit (sauvegardé)'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='saved_p_unit_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='prix unitaire (sauvegardé)'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='baskets.product', verbose_name='produit'),
        ),
        migrations.RunPython(init_order_item_saved_p, reverse_code=migrations.RunPython.noop),  # do nothing on reverse
    ]
