# Generated by Django 3.2.9 on 2023-05-04 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baskets', '0008_order_item_add_saved_p_fields_and_product_null_on_delete'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='products',
            field=models.ManyToManyField(help_text='A gauche tous les produits. A droite les produits disponibles à la commande pour cette livraison<br>', related_name='deliveries', to='baskets.Product', verbose_name='produits'),
        ),
    ]
