# Generated by Django 3.2.9 on 2023-05-21 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baskets', '0009_add_product_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='producer',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
